import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import RootProvider from "@/Context/RootProvider";
import QueryProvider from "@/Providers/queryProvider";
import { SocketProvider } from "@/Context/SocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" />
        <RootProvider>
          <SocketProvider>
            <QueryProvider>{children}</QueryProvider>
          </SocketProvider>
        </RootProvider>
      </body>
    </html>
  );
}
